{% set name = "r-essentials" %}
{% set version = "3.5.0" %}

{% set r_base_ver = '3.5.0' %}
{% set notebook_ver = '5.4.1' %}
{% set r_caret_ver = '6.0_79' %}
{% set r_data_table_ver = '1.10.4_3' %}
{% set r_dbi_ver = '0.7' %}
{% set r_formatr_ver = '1.55' %}
{% set r_glmnet_ver = '2.0_16' %}
{% set r_irkernel_ver = '0.8.11' %}
{% set r_plyr_ver = '1.8.4' %}
{% set r_quantmod_ver = '0.4_13' %}
{% set r_randomforest_ver = '4.6_14' %}
{% set r_rbokeh_ver = '0.6.3' %}
{% set r_recommended_ver = '3.5.0' %}
{% set r_reshape2_ver = '1.4.3' %}
{% set r_rmarkdown_ver = '1.9' %}
{% set r_shiny_ver = '1.0.5' %}
{% set r_tidyverse_ver = '1.2.1' %}
{% set r_zoo_ver = '1.8_0' %}

package:
  name: {{ name }}
  version: {{ version }}

requirements:
  build:
    - r-base >={{r_base_ver}}
    - notebook >={{notebook_ver}}
    - r-caret >={{r_caret_ver}}
    - r-data.table >={{r_data_table_ver}}
    - r-dbi >={{r_dbi_ver}}
    - r-formatr >={{r_formatr_ver}}
    - r-glmnet >={{r_glmnet_ver}}
    - r-irkernel >={{r_irkernel_ver}}
    - r-plyr >={{r_plyr_ver}}
    - r-quantmod >={{r_quantmod_ver}}
    - r-randomforest >={{r_randomforest_ver}}
    - r-rbokeh >={{r_rbokeh_ver}}
    - r-recommended >={{r_recommended_ver}}
    - r-reshape2 >={{r_reshape2_ver}}
    - r-rmarkdown >={{r_rmarkdown_ver}}
    - r-shiny >={{r_shiny_ver}}
    - r-tidyverse >={{r_tidyverse_ver}}
    - r-zoo >={{r_zoo_ver}}

  run:
    - r-base >={{r_base_ver}}
    - notebook >={{notebook_ver}}
    - r-caret >={{r_caret_ver}}
    - r-data.table >={{r_data_table_ver}}
    - r-dbi >={{r_dbi_ver}}
    - r-formatr >={{r_formatr_ver}}
    - r-glmnet >={{r_glmnet_ver}}
    - r-irkernel >={{r_irkernel_ver}}
    - r-plyr >={{r_plyr_ver}}
    - r-quantmod >={{r_quantmod_ver}}
    - r-randomforest >={{r_randomforest_ver}}
    - r-rbokeh >={{r_rbokeh_ver}}
    - r-recommended >={{r_recommended_ver}}
    - r-reshape2 >={{r_reshape2_ver}}
    - r-rmarkdown >={{r_rmarkdown_ver}}
    - r-shiny >={{r_shiny_ver}}
    - r-tidyverse >={{r_tidyverse_ver}}
    - r-zoo >={{r_zoo_ver}}

about:
  summary: "Some essential packages for working with R"
  license: Various
  license_family: Other

extra:
  recipe-maintainers:
    - bgruening
    - johanneskoester
    - mingwandroid
