travis:
  secure:
    BINSTAR_TOKEN: URSTpCBOlxh+lKdRHpG1Bg/uptLnr4oLcCEGhMpNP9p5VXbjkythgVqomLDAEe8bL/NDc4Mbz1eNI356wbSk6sG4SyBZvVLvEO+z43Fu0bFkgL8aSdgOhVwAgeJq2Z1YM66905I55c9emzvwJHIt0ya9LIamA8Vyth2MP4ct/1kweavXI6R9UwdtC4d7qPE4PQKe6sy0yYwzliqxrsHJnMwU9VunH7tUsjTeAzbvDqLuS0iCCeE92a71+LUb5NpqihTvIr38s15uMGck6/Odzn1SnMfVxxZVACBBI4UOGFUOzTM85SUd85Z0QaSNTB63EIuTyFzuOPyL18uWUaD5BQ5lFCvRwnVYN1WVdD0tGq1uszED1w3hCXRKCp8URTM7C5xwxOm+xSKSxKC2bz4nU6nRT3Os00YxcFLHTdUEUJcBjEM37iTe1SNHDEIY0TaNXvcB4OQcU84VZNAWRlZH9ZZDbRAyk2iKP/D3DT8BCzqHebC8K5lqidH7NnjJcyZMGcJJPIliSuLAqDblNt94WIEgs/9qCLRTwhouHVoVMK8MXtpL73Bism3yvxuyg1x2XnRnVKgbwIe7SVlEnTNwQxYwzNwtk7wekUQ3T1XYI4zq6TwkrXdpRwpwxDk3d3G+7edZWbEL7RaBJu5J7gD8dd85TrWA3+4cCzzOiNGlmww=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
