travis:
  secure:
    BINSTAR_TOKEN: dl/+VyZwXh5FLq7lH1qbVJW6kzRVkQ2NtGYIj/p1K63Fk1PQweo0NTfcBqoFOkd+oU0Z4qbpefmow1o6dd/XBhgFxVPp2w5qDcAl1DaI2RWJ8myx3mQFWDQD7X/P3v6eo6dLM8vtgT5r7CEzRAFvM73rJCtPGRZAPFw5NamYYdhxLJ0M+I3dRRylFrCXvnME0kc99Q4YZsL0xzrgYzlfIDktzrQrQ6DlBmlDZ1Ageuih0Xub7UEoqf17daMXCUyoDi4Ra45MuVmtWtPJ1Sj3xPS1LTaNiiEiWHdgT73DQXUduohs/CaVxn/qiFiaLmck4TzbWG0WRYjQcV+SEqad+UglAsc97y4x1YmTwZJTXE1DHOofXCF5/oK1kWBCC9sgM9Dp9p/af3zdH1HY0rFOEzfc+w+63TfEI6xCrHJ9mpvKDof8ashvX+kMBOV7f2ImeE/ZsOxpkaGwDEohk37cnYJy1C8j//PpfmOkRFrX7WjoWcpcpxY/yGTUfvz0QdvcxsaqAilST0+CWH1gbre4Y/cDowQjVxxxrVQl7fVzCrXAgPIR9fn+LKr4haU28LkdHHt/HMVdfUZDUaEbRoy4QPtBLv6oQLFg9HuYTQA7du8xcirC96gtfvKvgcOC0F8CHDlnx1U7bw0O7rAw9WhSgDVdiovRI+/ErxS202MjLsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
